### ISSUE TITLE
PSU and PJ weights

### ISSUE THREAD

**Issue by chenchen715** [nooreendabbish/Traffic#18]
According to Fan from GES, the reason that in the SAS code they provided, not three stages were listed out, was because they were using a simplified estimation of variance (simplifying multi-stage to one-stage). It is valid by approximating the first stage (PSU selection) "wiithout replacement" with "with replacement" option, so that it satisfies the prerequisites of Sarndal et al (1992) “Model assisted survey sampling” formula (4.5.3). Thus, the multistage design could be simplified by one-stage, in terms of variance estimation. 

SAS code shown as following:
/\* PSUSTRAT=13,14 ARE TWO CERTAINTY PSUS. */
DATA ALL_SELECTED_GES_ACCIDENT;
    SET ALL_GES_ACCIDENT;
    KEEP GES_YEAR CASENUM PSU PSUSTRAT WEIGHT MAN_COL INT_HWY TRAF_WAY  
        NUM_LAN ALIGN SUR_COND LGHT_CON WEATHER WRK_ZONE ALCOHOL;
    IF PSUSTRAT IN (13, 14) THEN PSU=PJ;
RUN; 

PROC SURVEYFREQ DATA=GES_BY_YEAR;
   STRATUM PSUSTRAT;
   CLUSTER PSU;
   TABLES MAN_COL INT_HWY TRAF_WAY NUM_LAN ALIGN SUR_COND LGHT_CON WEATHER WRK_ZONE ALCOHOL;
   WEIGHT WEIGHT;
RUN;

But we should continue with the multi-stage design we have, since it is not really time-consuming for us to run things with this design and it's in fact our purpose to use ROC/concordance in a multi-stage set up. Let me know if you agree with the conclusion.

Fan directed me to look into Sheldon's technical report Appendix D for PSU and PJ weights. But I found the values of PSU and PJ don't line up with what is in the data. I have drafted an email to follow up with this issue, will send first thing tomorrow. 

At the meantime, could you help me to understand where we stand on using the PSU and  PJ weights? Is ROC AUC estimation the only place where we would be using this information? Is it true that for now we only have the code to estimate the value, but haven't really generated a value based on data?

I will put in any information related to this issue in this thread going forward.

**Comment by PatrickCoyle** [comment]
Yes, we would use these weights to calculate the AUC statistic, which is equivalent to the concordance statistic for a binary response (according to Frank Harrell). Since concordance is also calculated by matching all possible pairs for true positives and true negatives, we should use the "joint weight" to calculate those as well. Actually, when you look at the formula for our weighted AUC estimation, it looks and feels exactly like concordance. We should see if Wenliang Yao mentions concordance in his dissertation.

I don't know of any other usage, although we could potentially use them to do mosaic plots that show the size differences within the 3-stage hierarchy.

**Comment by chenchen715** [comment]
Unfortunately we couldn't reproduce the PJ weights, and will need to guess for PSU weights... didn't move anywhere from our original plan, but it worth checking. I am closing this issue.

**Comment by chenchen715** [comment]
Haha, I actually
